---
- hosts: localhost
  connection: local
  tasks:
    - name: Clone the dot-git repository
      git:
        repo: https://github.com/mrxcitement/dot-git
        dest: ~/github/mrxcitement/dot-git
        clone: yes
        update: yes

    - name: Run install tasks from dot-git repository
      include_tasks: ~/github/mrxcitement/dot-git/install-tasks.yml

