---
- hosts: all
  tasks:
    - name: Clone the dot-git repository
      git:
        repo: https://github.com/mrxcitement/dot-git
        dest: /home/mike/github/mrxcitement/dot-git
        clone: yes
        update: yes

